### ISSUE TITLE
license, etc

### ISSUE THREAD

**Issue by colindaven** [nextflow-io/blast-example#2]
Hi,

we've heavily adapted a version of this script and added a bash wrapper to make blasting a subsection of fastqs easier.

I'm not sure what the license/ copyright is - would the author @pditommaso mind if we created a github project out of this work ?

Best wishes
Colin

**Comment by pditommaso** [comment]
Well, the license there's in the script 

https://github.com/nextflow-io/blast-example/blob/master/main.nf#L5-L22

**Comment by colindaven** [comment]
I see, thanks! I'm used to the license as different file
